const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("fluentAI", {
  status: (payload) => ipcRenderer.invoke("status", payload),
  keyStatus: () => ipcRenderer.invoke("key:status"),
  validateKey: (payload) => ipcRenderer.invoke("key:validate", payload),
  saveKey: (payload) => ipcRenderer.invoke("key:save", payload),
  deleteKey: () => ipcRenderer.invoke("key:delete"),
  onboardingStatus: (payload) => ipcRenderer.invoke("onboarding:status", payload),
  submitOnboarding: (payload) => ipcRenderer.invoke("onboarding:submit", payload),
  startPlacement: (payload) => ipcRenderer.invoke("placement:start", payload),
  submitPlacement: (payload) => ipcRenderer.invoke("placement:submit", payload),
  homeSummary: (payload) => ipcRenderer.invoke("home:summary", payload),
  memoryInspect: (payload) => ipcRenderer.invoke("memory:inspect", payload),
  memoryExport: (payload) => ipcRenderer.invoke("memory:export", payload),
  memoryResetLanguage: (payload) => ipcRenderer.invoke("memory:reset_language", payload),
  memoryDeleteAll: (payload) => ipcRenderer.invoke("memory:delete_all", payload),
  sessionCheckpoints: (payload) => ipcRenderer.invoke("session:checkpoints", payload),
  lessonCheckpoint: (payload) => ipcRenderer.invoke("lesson:checkpoint", payload),
  discardLessonCheckpoint: (payload) => ipcRenderer.invoke("lesson:checkpoint_discard", payload),
  callCheckpoint: (payload) => ipcRenderer.invoke("call:checkpoint", payload),
  discardCallCheckpoint: (payload) => ipcRenderer.invoke("call:checkpoint_discard", payload),
  summarizeCallCheckpoint: (payload) => ipcRenderer.invoke("call:checkpoint_summarize", payload),
  startLesson: (payload) => ipcRenderer.invoke("lesson:start", payload),
  submitLesson: (payload) => ipcRenderer.invoke("lesson:submit", payload),
  realtimeClientSecret: (payload) => ipcRenderer.invoke("realtime:client_secret", payload),
  analyzeCameraFrame: (payload) => ipcRenderer.invoke("vision:analyze_frame", payload),
  requestMediaAccess: (payload) => ipcRenderer.invoke("media:request_access", payload),
  mediaDiagnostics: () => ipcRenderer.invoke("media:diagnostics"),
  startConversation: (options) => ipcRenderer.invoke("conversation:start", options),
  replyConversation: (payload) => ipcRenderer.invoke("conversation:reply", payload),
  endConversation: (payload) => ipcRenderer.invoke("conversation:end", payload)
});
